"""init

Revision ID: a04416395522
Revises: 
Create Date: 2022-04-19 21:47:41.305941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04416395522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_plate',
    sa.Column('reg_number', sa.String(length=64), nullable=False),
    sa.Column('reg_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('reg_number')
    )
    op.create_index(op.f('ix_number_plate_reg_number'), 'number_plate', ['reg_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_number_plate_reg_number'), table_name='number_plate')
    op.drop_table('number_plate')
    # ### end Alembic commands ###
